ARG AIRFLOW_IMAGE_NAME
FROM $AIRFLOW_IMAGE_NAME
RUN pip install --upgrade pip
RUN pip install scikit-learn==0.24.2
RUN pip install pyarrow==5.0.0
RUN pip install mlflow==1.20.2
RUN pip install hyperopt==0.2.5
